### PR TITLE
Add the ability to emit the notes field.

### PR DESCRIPTION
**Pull request by gsker**
Sometimes I wish I could just emit the notes field.  
I suppose I should have created an issue first....?

### CODE REVIEW

**Comment by sakhnik** [comment]
Thanks for the patch!
Now you have push rights to the repository.
Suggestions:
- Update Ukrainian translation with the new strings added (probably, I could do that as a native speaker)
- Fix travis automatic build

**Comment by gsker** [comment]
Is there a regular travis build configured?
Where is the travis build happening?
Does it support bionic (ubuntu 18.04)?

The switch to bionic would want a few changes:

dist: bionic
before_install:
    googetest instead of libgtest-dev
    g++-7  instead of g++-5


--
gsker@skerbitz.org

**Comment by sakhnik** [comment]
First of all, there is a make target update-po in the build directory po.
It updates po files for every languate defined. This could also be improved
to update translations for a single language.
Then to add a new language you just need to create a new file with the
respective name and correct header (can be copied and adjusted from the
existing ones).
Personally I edit po files in Vim/NeoVim. And unfortunately, I'm not aware
of any dedicated specific tools.

сб, 8 вер. 2018 о 21:20 Gerry Skerbitz <notifications@github.com> пише:

**Comment by sakhnik** [comment]
Yes, the build is configured in the .travis.yml in the root directory.
Every git push triggers a build at http://travis-ci.org. I believe you can
observe the log and the result of the build following the link in README.md.
If it's necessary to update to a newer release of Ubuntu, please do so. But
I was convinced for some reason, that they supported only trusty.

сб, 8 вер. 2018 о 21:28 Gerry Skerbitz <notifications@github.com> пише:

**Comment by sakhnik** [comment]
By the way, I've just updated Ukrainian translation. So no worries with this one.

**Comment by gsker** [comment]
You're right about the travis build using trusty.


--
gsker@skerbitz.org

**Pull request merged**
