### PR TITLE
Add CMAKE_THREAD_LIBS_INIT to libraries

### PR DESCRIPTION
**Pull request by gsker**

### CODE REVIEW

**Comment by sakhnik** [comment]
Looks good for me.
Are you able to merge it on your own?

**Comment by gsker** [comment]
I was going to try to merge it.   Still not very adept at this.  I see the travis build failed. At least I know where it is now: :-D

**Comment by gsker** [comment]
Although it works in my local trusty install, it clearly doesn't in the travis build.  I'm closing it.  Maybe it needs a comment somewhere as a hint for local builds.  The Issue is there anyway if someone goes looking.

**Comment by sakhnik** [comment]
Why? Your change is needed in a general case too.
To fix the travis build, one need to investigate why the cmake couldn't find GTest even though it was supposedly installed with `apt-get install -y libgtest-dev`.

**Comment by gsker** [comment]
I would think so. That's why I installed a local copy of trusty.  It's not close enough though because I was unable to make it fail.  What's the debug mechanism? Do you just change the travis.yml file to get it to spit out more logs?

**Comment by sakhnik** [comment]
Yes, that's the only way.
You can also manipulate `CMakeLists.txt` to print more or even cat cmake
logs (`"cmake || cat whatever.log"`).

нд, 9 вер. 2018 о 00:34 Gerry Skerbitz <notifications@github.com> пише:

**Comment by gsker** [comment]
The root cause:  No cmake command in the path:

[0K$ cd /usr/src/gtest && sudo cmake 
-DBUILD_SHARED_LIBS=ON . && sudo make && 
sudo mv libg* /usr/local/lib/; cd -
sudo: cmake: command not found

But that makes no sense since after making the BUILD directory, then next thing 
that happens is

[32;1mThe command "cd BUILD" exited with 0.[0m
travis_time:start:1fdac12e
[0K$ cmake ..
-- The C compiler identification is GNU 5.5.0

And _that_  cmake command works.

Well I have something to work with anyway....
Thanks for the help.



--
gsker@skerbitz.org

**Comment by sakhnik** [comment]
You were really close. It can happen that `cmake` and `sudo cmake` yield different results. After all, the commands are picked up from the environment variable `PATH`. Apparently, the Travis CI team have changed the way sudo works.
The last "; cd -" in that long command masked the failed `sudo cmake`, so it was harder to notice.
To fix the issues, I did the following:
- Copy `/usr/src/gtest` to a temporary directory with user access
- Build with `cmake` without `sudo`
- Finally, get rid of `; cd -`

Thanks for cooperation!

**Comment by sakhnik** [comment]
Please consider committing your change with `CMAKE_THREAD_LIBS_INIT`. The change is reasonable.

**Comment by gsker** [comment]
:-(  I wanted to solve it by myself.    :-D
I am so not up to speed with travis.  I'll keep learning though.  

I'll make a new pull request and then  commit it for the test/CMakeList.txt change.  Thanks!

**Comment by gsker** [comment]
I recreated the branch in my repo and will just re-open this pull request instead of making a new one.

**Comment by gsker** [comment]
Looks like I don't have enough rights to merge. It says 
```
Only those with write access to this repository can merge pull requests.
```
And I don't have a merge pull request button: https://help.github.com/assets/images/help/pull_requests/pullrequest-mergebutton.png

**Comment by gsker** [comment]
Okay. I merged the travis branch into my googletest-libfix branch and then the travis build kicked off automatically. Not what I expected but it's all working.  So I guess I have to wait for  you to hit the "Merge Pull Request"  button, right?

**Comment by sakhnik** [comment]
You should have received an invitation. Github says me you haven't accepted it yet, so no push rights.

**Comment by gsker** [comment]
Ah.  I missed the invitation.   I found it in my email and accepted it.


--
gsker@skerbitz.org

**Pull request merged**
